Add json output to action.yml
docker/metadata-action pull request #167
Opened 2022-02-18 18:59 UTC by StefanSchoof

Resolves #166

2022-03-06 07:54 UTC, crazy-max requested changes

2022-03-06 07:54 UTC, crazy-max commented on action.yml
> +    description: 'A JSON object composed of the generated tags and labels'
Better to keep the same desc of the README: https://github.com/docker/metadata-action#outputs

```suggestion
    description: 'JSON output of tags and labels'
```

2022-03-06 08:07 UTC, StefanSchoof commented
Okay, did this via web from my phone. The DCO seems not to like this. Will try to take a look, when I at my PC. Probably not today

2022-03-07 06:45 UTC, crazy-max commented
> Okay, did this via web from my phone. The DCO seems not to like this. Will try to take a look, when I at my PC. Probably not today

Yes and also squash commits, thx.

2022-03-08 10:57 UTC, crazy-max approved these changes
LGTM thanks

2022-03-08 10:57 UTC, merged